### ISSUE TITLE
pipenv can be more convenient for installation

### ISSUE THREAD

**Issue by jungyitsai** [peter279k/iii_tmp_passwd_tool#1]
- pipenv doc
  - https://medium.com/@chihsuan/pipenv-%E6%9B%B4%E7%B0%A1%E5%96%AE-%E6%9B%B4%E5%BF%AB%E9%80%9F%E7%9A%84-python-%E5%A5%97%E4%BB%B6%E7%AE%A1%E7%90%86%E5%B7%A5%E5%85%B7-135a47e504f4

**Comment by peter279k** [comment]
Thanks for your reply. I prefer using the `pyenv` and `virtualenv` to create the virtual Python runtime environment.

Anyways, thanks for your sharing :).

**Comment by peter279k** [comment]
Closed via 8d0d2b0658c887784ff21641e91fa131f7c347fa.
